/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusContainer } from './RequestRateLimitStatusContainer';
import {
    RequestRateLimitStatusContainerFromJSON,
    RequestRateLimitStatusContainerFromJSONTyped,
    RequestRateLimitStatusContainerToJSON,
} from './RequestRateLimitStatusContainer';
import type { RequestRateLimitStatusContainerTypeInfo } from './RequestRateLimitStatusContainerTypeInfo';
import {
    RequestRateLimitStatusContainerTypeInfoFromJSON,
    RequestRateLimitStatusContainerTypeInfoFromJSONTyped,
    RequestRateLimitStatusContainerTypeInfoToJSON,
} from './RequestRateLimitStatusContainerTypeInfo';
import type { RequestRateLimitStatusPerTimeUnitInfo } from './RequestRateLimitStatusPerTimeUnitInfo';
import {
    RequestRateLimitStatusPerTimeUnitInfoFromJSON,
    RequestRateLimitStatusPerTimeUnitInfoFromJSONTyped,
    RequestRateLimitStatusPerTimeUnitInfoToJSON,
} from './RequestRateLimitStatusPerTimeUnitInfo';

/**
 * 
 * @export
 * @interface RequestRateLimitStatus
 */
export interface RequestRateLimitStatus {
    /**
     * 
     * @type {Array<RequestRateLimitStatusContainerTypeInfo>}
     * @memberof RequestRateLimitStatus
     */
    readonly containerTypeInfos?: Array<RequestRateLimitStatusContainerTypeInfo> | null;
    /**
     * 
     * @type {{ [key: string]: RequestRateLimitStatusPerTimeUnitInfo; }}
     * @memberof RequestRateLimitStatus
     */
    perUnitInfos?: { [key: string]: RequestRateLimitStatusPerTimeUnitInfo; } | null;
    /**
     * 
     * @type {Date}
     * @memberof RequestRateLimitStatus
     */
    updatedTime?: Date;
    /**
     * 
     * @type {{ [key: string]: Array<RequestRateLimitStatusContainer>; }}
     * @memberof RequestRateLimitStatus
     */
    containerTypesContainers?: { [key: string]: Array<RequestRateLimitStatusContainer>; } | null;
}

/**
 * Check if a given object implements the RequestRateLimitStatus interface.
 */
export function instanceOfRequestRateLimitStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusFromJSON(json: any): RequestRateLimitStatus {
    return RequestRateLimitStatusFromJSONTyped(json, false);
}

export function RequestRateLimitStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'containerTypeInfos': !exists(json, 'containerTypeInfos') ? undefined : (json['containerTypeInfos'] === null ? null : (json['containerTypeInfos'] as Array<any>).map(RequestRateLimitStatusContainerTypeInfoFromJSON)),
        'perUnitInfos': !exists(json, 'perUnitInfos') ? undefined : (json['perUnitInfos'] === null ? null : mapValues(json['perUnitInfos'], RequestRateLimitStatusPerTimeUnitInfoFromJSON)),
        'updatedTime': !exists(json, 'updatedTime') ? undefined : (new Date(json['updatedTime'])),
        'containerTypesContainers': !exists(json, 'containerTypesContainers') ? undefined : json['containerTypesContainers'],
    };
}

export function RequestRateLimitStatusToJSON(value?: RequestRateLimitStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'perUnitInfos': value.perUnitInfos === undefined ? undefined : (value.perUnitInfos === null ? null : mapValues(value.perUnitInfos, RequestRateLimitStatusPerTimeUnitInfoToJSON)),
        'updatedTime': value.updatedTime === undefined ? undefined : (value.updatedTime.toISOString()),
        'containerTypesContainers': value.containerTypesContainers,
    };
}

