/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusContainerTypeInfo } from './RequestRateLimitStatusContainerTypeInfo';
import {
    RequestRateLimitStatusContainerTypeInfoFromJSON,
    RequestRateLimitStatusContainerTypeInfoFromJSONTyped,
    RequestRateLimitStatusContainerTypeInfoToJSON,
} from './RequestRateLimitStatusContainerTypeInfo';
import type { RequestRateLimitStatusPerTimeUnitInfo } from './RequestRateLimitStatusPerTimeUnitInfo';
import {
    RequestRateLimitStatusPerTimeUnitInfoFromJSON,
    RequestRateLimitStatusPerTimeUnitInfoFromJSONTyped,
    RequestRateLimitStatusPerTimeUnitInfoToJSON,
} from './RequestRateLimitStatusPerTimeUnitInfo';

/**
 * 
 * @export
 * @interface RequestRateLimitStatusInfo
 */
export interface RequestRateLimitStatusInfo {
    /**
     * 
     * @type {Array<RequestRateLimitStatusContainerTypeInfo>}
     * @memberof RequestRateLimitStatusInfo
     */
    typeInfos?: Array<RequestRateLimitStatusContainerTypeInfo> | null;
    /**
     * 
     * @type {{ [key: string]: RequestRateLimitStatusPerTimeUnitInfo; }}
     * @memberof RequestRateLimitStatusInfo
     */
    unitUnitInfos?: { [key: string]: RequestRateLimitStatusPerTimeUnitInfo; } | null;
}

/**
 * Check if a given object implements the RequestRateLimitStatusInfo interface.
 */
export function instanceOfRequestRateLimitStatusInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusInfoFromJSON(json: any): RequestRateLimitStatusInfo {
    return RequestRateLimitStatusInfoFromJSONTyped(json, false);
}

export function RequestRateLimitStatusInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatusInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typeInfos': !exists(json, 'typeInfos') ? undefined : (json['typeInfos'] === null ? null : (json['typeInfos'] as Array<any>).map(RequestRateLimitStatusContainerTypeInfoFromJSON)),
        'unitUnitInfos': !exists(json, 'unitUnitInfos') ? undefined : (json['unitUnitInfos'] === null ? null : mapValues(json['unitUnitInfos'], RequestRateLimitStatusPerTimeUnitInfoFromJSON)),
    };
}

export function RequestRateLimitStatusInfoToJSON(value?: RequestRateLimitStatusInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'typeInfos': value.typeInfos === undefined ? undefined : (value.typeInfos === null ? null : (value.typeInfos as Array<any>).map(RequestRateLimitStatusContainerTypeInfoToJSON)),
        'unitUnitInfos': value.unitUnitInfos === undefined ? undefined : (value.unitUnitInfos === null ? null : mapValues(value.unitUnitInfos, RequestRateLimitStatusPerTimeUnitInfoToJSON)),
    };
}

