/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusContainerTypeInfo } from './RequestRateLimitStatusContainerTypeInfo';
import {
    RequestRateLimitStatusContainerTypeInfoFromJSON,
    RequestRateLimitStatusContainerTypeInfoFromJSONTyped,
    RequestRateLimitStatusContainerTypeInfoToJSON,
} from './RequestRateLimitStatusContainerTypeInfo';
import type { RequestRateLimitStatusPerTimeUnitInfo } from './RequestRateLimitStatusPerTimeUnitInfo';
import {
    RequestRateLimitStatusPerTimeUnitInfoFromJSON,
    RequestRateLimitStatusPerTimeUnitInfoFromJSONTyped,
    RequestRateLimitStatusPerTimeUnitInfoToJSON,
} from './RequestRateLimitStatusPerTimeUnitInfo';

/**
 * 
 * @export
 * @interface RequestRateLimitStatusInfo
 */
export interface RequestRateLimitStatusInfo {
    /**
     * 
     * @type {Array<RequestRateLimitStatusContainerTypeInfo>}
     * @memberof RequestRateLimitStatusInfo
     */
    containerTypeInfos?: Array<RequestRateLimitStatusContainerTypeInfo> | null;
    /**
     * 
     * @type {{ [key: string]: RequestRateLimitStatusPerTimeUnitInfo; }}
     * @memberof RequestRateLimitStatusInfo
     */
    perUnitInfos?: { [key: string]: RequestRateLimitStatusPerTimeUnitInfo; } | null;
}

/**
 * Check if a given object implements the RequestRateLimitStatusInfo interface.
 */
export function instanceOfRequestRateLimitStatusInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusInfoFromJSON(json: any): RequestRateLimitStatusInfo {
    return RequestRateLimitStatusInfoFromJSONTyped(json, false);
}

export function RequestRateLimitStatusInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatusInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'containerTypeInfos': !exists(json, 'containerTypeInfos') ? undefined : (json['containerTypeInfos'] === null ? null : (json['containerTypeInfos'] as Array<any>).map(RequestRateLimitStatusContainerTypeInfoFromJSON)),
        'perUnitInfos': !exists(json, 'perUnitInfos') ? undefined : (json['perUnitInfos'] === null ? null : mapValues(json['perUnitInfos'], RequestRateLimitStatusPerTimeUnitInfoFromJSON)),
    };
}

export function RequestRateLimitStatusInfoToJSON(value?: RequestRateLimitStatusInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'containerTypeInfos': value.containerTypeInfos === undefined ? undefined : (value.containerTypeInfos === null ? null : (value.containerTypeInfos as Array<any>).map(RequestRateLimitStatusContainerTypeInfoToJSON)),
        'perUnitInfos': value.perUnitInfos === undefined ? undefined : (value.perUnitInfos === null ? null : mapValues(value.perUnitInfos, RequestRateLimitStatusPerTimeUnitInfoToJSON)),
    };
}

