/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RequestRateLimitStatusPerTimeUnit = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type RequestRateLimitStatusPerTimeUnit = typeof RequestRateLimitStatusPerTimeUnit[keyof typeof RequestRateLimitStatusPerTimeUnit];


export function RequestRateLimitStatusPerTimeUnitFromJSON(json: any): RequestRateLimitStatusPerTimeUnit {
    return RequestRateLimitStatusPerTimeUnitFromJSONTyped(json, false);
}

export function RequestRateLimitStatusPerTimeUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatusPerTimeUnit {
    return json as RequestRateLimitStatusPerTimeUnit;
}

export function RequestRateLimitStatusPerTimeUnitToJSON(value?: RequestRateLimitStatusPerTimeUnit | null): any {
    return value as any;
}

