/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusPerTimeUnit } from './RequestRateLimitStatusPerTimeUnit';
import {
    RequestRateLimitStatusPerTimeUnitFromJSON,
    RequestRateLimitStatusPerTimeUnitFromJSONTyped,
    RequestRateLimitStatusPerTimeUnitToJSON,
} from './RequestRateLimitStatusPerTimeUnit';

/**
 * 
 * @export
 * @interface RequestRateLimitStatusContainerItem
 */
export interface RequestRateLimitStatusContainerItem {
    /**
     * 
     * @type {RequestRateLimitStatusPerTimeUnit}
     * @memberof RequestRateLimitStatusContainerItem
     */
    perTimeUnit?: RequestRateLimitStatusPerTimeUnit;
    /**
     * 
     * @type {number}
     * @memberof RequestRateLimitStatusContainerItem
     */
    limitTimes?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestRateLimitStatusContainerItem
     */
    capacity?: number;
}

/**
 * Check if a given object implements the RequestRateLimitStatusContainerItem interface.
 */
export function instanceOfRequestRateLimitStatusContainerItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusContainerItemFromJSON(json: any): RequestRateLimitStatusContainerItem {
    return RequestRateLimitStatusContainerItemFromJSONTyped(json, false);
}

export function RequestRateLimitStatusContainerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatusContainerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'perTimeUnit': !exists(json, 'perTimeUnit') ? undefined : RequestRateLimitStatusPerTimeUnitFromJSON(json['perTimeUnit']),
        'limitTimes': !exists(json, 'limitTimes') ? undefined : json['limitTimes'],
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
    };
}

export function RequestRateLimitStatusContainerItemToJSON(value?: RequestRateLimitStatusContainerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'perTimeUnit': RequestRateLimitStatusPerTimeUnitToJSON(value.perTimeUnit),
        'limitTimes': value.limitTimes,
        'capacity': value.capacity,
    };
}

