/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusContainer } from './RequestRateLimitStatusContainer';
import {
    RequestRateLimitStatusContainerFromJSON,
    RequestRateLimitStatusContainerFromJSONTyped,
    RequestRateLimitStatusContainerToJSON,
} from './RequestRateLimitStatusContainer';

/**
 * 
 * @export
 * @interface RequestRateLimitStatus
 */
export interface RequestRateLimitStatus {
    /**
     * 
     * @type {Date}
     * @memberof RequestRateLimitStatus
     */
    updatedTime?: Date;
    /**
     * 
     * @type {{ [key: string]: Array<RequestRateLimitStatusContainer>; }}
     * @memberof RequestRateLimitStatus
     */
    typesContainers?: { [key: string]: Array<RequestRateLimitStatusContainer>; } | null;
}

/**
 * Check if a given object implements the RequestRateLimitStatus interface.
 */
export function instanceOfRequestRateLimitStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusFromJSON(json: any): RequestRateLimitStatus {
    return RequestRateLimitStatusFromJSONTyped(json, false);
}

export function RequestRateLimitStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updatedTime': !exists(json, 'updatedTime') ? undefined : (new Date(json['updatedTime'])),
        'typesContainers': !exists(json, 'typesContainers') ? undefined : json['typesContainers'],
    };
}

export function RequestRateLimitStatusToJSON(value?: RequestRateLimitStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updatedTime': value.updatedTime === undefined ? undefined : (value.updatedTime.toISOString()),
        'typesContainers': value.typesContainers,
    };
}

