/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestRateLimitStatusPerTimeUnit } from './RequestRateLimitStatusPerTimeUnit';
import {
    RequestRateLimitStatusPerTimeUnitFromJSON,
    RequestRateLimitStatusPerTimeUnitFromJSONTyped,
    RequestRateLimitStatusPerTimeUnitToJSON,
} from './RequestRateLimitStatusPerTimeUnit';

/**
 * 
 * @export
 * @interface RequestRateLimitStatusPerTimeUnitInfo
 */
export interface RequestRateLimitStatusPerTimeUnitInfo {
    /**
     * 
     * @type {RequestRateLimitStatusPerTimeUnit}
     * @memberof RequestRateLimitStatusPerTimeUnitInfo
     */
    unit?: RequestRateLimitStatusPerTimeUnit;
    /**
     * 
     * @type {string}
     * @memberof RequestRateLimitStatusPerTimeUnitInfo
     */
    name?: string | null;
}

/**
 * Check if a given object implements the RequestRateLimitStatusPerTimeUnitInfo interface.
 */
export function instanceOfRequestRateLimitStatusPerTimeUnitInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRateLimitStatusPerTimeUnitInfoFromJSON(json: any): RequestRateLimitStatusPerTimeUnitInfo {
    return RequestRateLimitStatusPerTimeUnitInfoFromJSONTyped(json, false);
}

export function RequestRateLimitStatusPerTimeUnitInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRateLimitStatusPerTimeUnitInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unit': !exists(json, 'unit') ? undefined : RequestRateLimitStatusPerTimeUnitFromJSON(json['unit']),
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function RequestRateLimitStatusPerTimeUnitInfoToJSON(value?: RequestRateLimitStatusPerTimeUnitInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unit': RequestRateLimitStatusPerTimeUnitToJSON(value.unit),
        'name': value.name,
    };
}

