/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatusPerTimeUnitInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusPerTimeUnitInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatusPerTimeUnitInfo
        //private RequestRateLimitStatusPerTimeUnitInfo instance;

        public RequestRateLimitStatusPerTimeUnitInfoTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatusPerTimeUnitInfo
            //instance = new RequestRateLimitStatusPerTimeUnitInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatusPerTimeUnitInfo
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusPerTimeUnitInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatusPerTimeUnitInfo
            //Assert.IsType<RequestRateLimitStatusPerTimeUnitInfo>(instance);
        }

        /// <summary>
        /// Test the property 'PerTimeUnit'
        /// </summary>
        [Fact]
        public void PerTimeUnitTest()
        {
            // TODO unit test for the property 'PerTimeUnit'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
