/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatusInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatusInfo
        //private RequestRateLimitStatusInfo instance;

        public RequestRateLimitStatusInfoTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatusInfo
            //instance = new RequestRateLimitStatusInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatusInfo
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatusInfo
            //Assert.IsType<RequestRateLimitStatusInfo>(instance);
        }

        /// <summary>
        /// Test the property 'TypeInfos'
        /// </summary>
        [Fact]
        public void TypeInfosTest()
        {
            // TODO unit test for the property 'TypeInfos'
        }

        /// <summary>
        /// Test the property 'UnitUnitInfos'
        /// </summary>
        [Fact]
        public void UnitUnitInfosTest()
        {
            // TODO unit test for the property 'UnitUnitInfos'
        }
    }
}
