/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatus
        //private RequestRateLimitStatus instance;

        public RequestRateLimitStatusTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatus
            //instance = new RequestRateLimitStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatus
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatus
            //Assert.IsType<RequestRateLimitStatus>(instance);
        }

        /// <summary>
        /// Test the property 'ContainerTypeInfos'
        /// </summary>
        [Fact]
        public void ContainerTypeInfosTest()
        {
            // TODO unit test for the property 'ContainerTypeInfos'
        }

        /// <summary>
        /// Test the property 'PerUnitInfos'
        /// </summary>
        [Fact]
        public void PerUnitInfosTest()
        {
            // TODO unit test for the property 'PerUnitInfos'
        }

        /// <summary>
        /// Test the property 'UpdatedTime'
        /// </summary>
        [Fact]
        public void UpdatedTimeTest()
        {
            // TODO unit test for the property 'UpdatedTime'
        }

        /// <summary>
        /// Test the property 'ContainerTypesContainers'
        /// </summary>
        [Fact]
        public void ContainerTypesContainersTest()
        {
            // TODO unit test for the property 'ContainerTypesContainers'
        }
    }
}
