/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatusContainerItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusContainerItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatusContainerItem
        //private RequestRateLimitStatusContainerItem instance;

        public RequestRateLimitStatusContainerItemTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatusContainerItem
            //instance = new RequestRateLimitStatusContainerItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatusContainerItem
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusContainerItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatusContainerItem
            //Assert.IsType<RequestRateLimitStatusContainerItem>(instance);
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
