/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatusContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatusContainer
        //private RequestRateLimitStatusContainer instance;

        public RequestRateLimitStatusContainerTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatusContainer
            //instance = new RequestRateLimitStatusContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatusContainer
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatusContainer
            //Assert.IsType<RequestRateLimitStatusContainer>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'UpdatedTime'
        /// </summary>
        [Fact]
        public void UpdatedTimeTest()
        {
            // TODO unit test for the property 'UpdatedTime'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
