/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestRateLimitStatusContainerTypeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestRateLimitStatusContainerTypeInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestRateLimitStatusContainerTypeInfo
        //private RequestRateLimitStatusContainerTypeInfo instance;

        public RequestRateLimitStatusContainerTypeInfoTests()
        {
            // TODO uncomment below to create an instance of RequestRateLimitStatusContainerTypeInfo
            //instance = new RequestRateLimitStatusContainerTypeInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestRateLimitStatusContainerTypeInfo
        /// </summary>
        [Fact]
        public void RequestRateLimitStatusContainerTypeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestRateLimitStatusContainerTypeInfo
            //Assert.IsType<RequestRateLimitStatusContainerTypeInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
