/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RequestRateLimitStatusInfo
    /// </summary>
    [DataContract(Name = "RequestRateLimitStatusInfo")]
    public partial class RequestRateLimitStatusInfo : IEquatable<RequestRateLimitStatusInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestRateLimitStatusInfo" /> class.
        /// </summary>
        /// <param name="typeInfos">typeInfos.</param>
        /// <param name="unitUnitInfos">unitUnitInfos.</param>
        public RequestRateLimitStatusInfo(List<RequestRateLimitStatusContainerTypeInfo> typeInfos = default(List<RequestRateLimitStatusContainerTypeInfo>), Dictionary<string, RequestRateLimitStatusPerTimeUnitInfo> unitUnitInfos = default(Dictionary<string, RequestRateLimitStatusPerTimeUnitInfo>))
        {
            this.TypeInfos = typeInfos;
            this.UnitUnitInfos = unitUnitInfos;
        }

        /// <summary>
        /// Gets or Sets TypeInfos
        /// </summary>
        [DataMember(Name = "typeInfos", EmitDefaultValue = true)]
        public List<RequestRateLimitStatusContainerTypeInfo> TypeInfos { get; set; }

        /// <summary>
        /// Gets or Sets UnitUnitInfos
        /// </summary>
        [DataMember(Name = "unitUnitInfos", EmitDefaultValue = true)]
        public Dictionary<string, RequestRateLimitStatusPerTimeUnitInfo> UnitUnitInfos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestRateLimitStatusInfo {\n");
            sb.Append("  TypeInfos: ").Append(TypeInfos).Append("\n");
            sb.Append("  UnitUnitInfos: ").Append(UnitUnitInfos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestRateLimitStatusInfo);
        }

        /// <summary>
        /// Returns true if RequestRateLimitStatusInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestRateLimitStatusInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestRateLimitStatusInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TypeInfos == input.TypeInfos ||
                    this.TypeInfos != null &&
                    input.TypeInfos != null &&
                    this.TypeInfos.SequenceEqual(input.TypeInfos)
                ) && 
                (
                    this.UnitUnitInfos == input.UnitUnitInfos ||
                    this.UnitUnitInfos != null &&
                    input.UnitUnitInfos != null &&
                    this.UnitUnitInfos.SequenceEqual(input.UnitUnitInfos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TypeInfos != null)
                {
                    hashCode = (hashCode * 59) + this.TypeInfos.GetHashCode();
                }
                if (this.UnitUnitInfos != null)
                {
                    hashCode = (hashCode * 59) + this.UnitUnitInfos.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
