/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RequestRateLimitStatusContainerItem
    /// </summary>
    [DataContract(Name = "RequestRateLimitStatusContainerItem")]
    public partial class RequestRateLimitStatusContainerItem : IEquatable<RequestRateLimitStatusContainerItem>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets PerTimeUnit
        /// </summary>
        [DataMember(Name = "perTimeUnit", EmitDefaultValue = false)]
        public RequestRateLimitStatusPerTimeUnit? PerTimeUnit { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestRateLimitStatusContainerItem" /> class.
        /// </summary>
        /// <param name="perTimeUnit">perTimeUnit.</param>
        /// <param name="limitTimes">limitTimes.</param>
        /// <param name="capacity">capacity.</param>
        public RequestRateLimitStatusContainerItem(RequestRateLimitStatusPerTimeUnit? perTimeUnit = default(RequestRateLimitStatusPerTimeUnit?), int limitTimes = default(int), int capacity = default(int))
        {
            this.PerTimeUnit = perTimeUnit;
            this.LimitTimes = limitTimes;
            this.Capacity = capacity;
        }

        /// <summary>
        /// Gets or Sets LimitTimes
        /// </summary>
        [DataMember(Name = "limitTimes", EmitDefaultValue = false)]
        public int LimitTimes { get; set; }

        /// <summary>
        /// Gets or Sets Capacity
        /// </summary>
        [DataMember(Name = "capacity", EmitDefaultValue = false)]
        public int Capacity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestRateLimitStatusContainerItem {\n");
            sb.Append("  PerTimeUnit: ").Append(PerTimeUnit).Append("\n");
            sb.Append("  LimitTimes: ").Append(LimitTimes).Append("\n");
            sb.Append("  Capacity: ").Append(Capacity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestRateLimitStatusContainerItem);
        }

        /// <summary>
        /// Returns true if RequestRateLimitStatusContainerItem instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestRateLimitStatusContainerItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestRateLimitStatusContainerItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PerTimeUnit == input.PerTimeUnit ||
                    this.PerTimeUnit.Equals(input.PerTimeUnit)
                ) && 
                (
                    this.LimitTimes == input.LimitTimes ||
                    this.LimitTimes.Equals(input.LimitTimes)
                ) && 
                (
                    this.Capacity == input.Capacity ||
                    this.Capacity.Equals(input.Capacity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PerTimeUnit.GetHashCode();
                hashCode = (hashCode * 59) + this.LimitTimes.GetHashCode();
                hashCode = (hashCode * 59) + this.Capacity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
