/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CountApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CountApiTests : IDisposable
    {
        private CountApi instance;

        public CountApiTests()
        {
            instance = new CountApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CountApi
            //Assert.IsType<CountApi>(instance);
        }

        /// <summary>
        /// Test ApiCountGetNormalGet
        /// </summary>
        [Fact]
        public void ApiCountGetNormalGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? data = null;
            //var response = instance.ApiCountGetNormalGet(data);
            //Assert.IsType<int>(response);
        }
    }
}
