/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LimitUserAction3s5m100hApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LimitUserAction3s5m100hApiTests : IDisposable
    {
        private LimitUserAction3s5m100hApi instance;

        public LimitUserAction3s5m100hApiTests()
        {
            instance = new LimitUserAction3s5m100hApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LimitUserAction3s5m100hApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LimitUserAction3s5m100hApi
            //Assert.IsType<LimitUserAction3s5m100hApi>(instance);
        }

        /// <summary>
        /// Test ApiLimitUserAction3s5m100hGetGet
        /// </summary>
        [Fact]
        public void ApiLimitUserAction3s5m100hGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiLimitUserAction3s5m100hGetGet();
            //Assert.IsType<string>(response);
        }
    }
}
