/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LimitController3sApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LimitController3sApiTests : IDisposable
    {
        private LimitController3sApi instance;

        public LimitController3sApiTests()
        {
            instance = new LimitController3sApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LimitController3sApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LimitController3sApi
            //Assert.IsType<LimitController3sApi>(instance);
        }

        /// <summary>
        /// Test ApiLimitController3sGetGet
        /// </summary>
        [Fact]
        public void ApiLimitController3sGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiLimitController3sGetGet();
            //Assert.IsType<string>(response);
        }
    }
}
