/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LimitGlobal3PerSecond5PerMinute4PerMinuteApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LimitGlobal3PerSecond5PerMinute4PerMinuteApiTests : IDisposable
    {
        private LimitGlobal3PerSecond5PerMinute4PerMinuteApi instance;

        public LimitGlobal3PerSecond5PerMinute4PerMinuteApiTests()
        {
            instance = new LimitGlobal3PerSecond5PerMinute4PerMinuteApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LimitGlobal3PerSecond5PerMinute4PerMinuteApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LimitGlobal3PerSecond5PerMinute4PerMinuteApi
            //Assert.IsType<LimitGlobal3PerSecond5PerMinute4PerMinuteApi>(instance);
        }

        /// <summary>
        /// Test ApiLimitGlobal3PerSecond5PerMinute4PerMinuteGetNormalGet
        /// </summary>
        [Fact]
        public void ApiLimitGlobal3PerSecond5PerMinute4PerMinuteGetNormalGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? data = null;
            //var response = instance.ApiLimitGlobal3PerSecond5PerMinute4PerMinuteGetNormalGet(data);
            //Assert.IsType<string>(response);
        }
    }
}
