/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LimitIpController3s5mApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LimitIpController3s5mApiTests : IDisposable
    {
        private LimitIpController3s5mApi instance;

        public LimitIpController3s5mApiTests()
        {
            instance = new LimitIpController3s5mApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LimitIpController3s5mApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LimitIpController3s5mApi
            //Assert.IsType<LimitIpController3s5mApi>(instance);
        }

        /// <summary>
        /// Test ApiLimitIpController3s5mGetGet
        /// </summary>
        [Fact]
        public void ApiLimitIpController3s5mGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiLimitIpController3s5mGetGet();
            //Assert.IsType<string>(response);
        }
    }
}
