/*
 * SampleLimitRequestWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LimitUserController3s5m4mApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LimitUserController3s5m4mApiTests : IDisposable
    {
        private LimitUserController3s5m4mApi instance;

        public LimitUserController3s5m4mApiTests()
        {
            instance = new LimitUserController3s5m4mApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LimitUserController3s5m4mApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LimitUserController3s5m4mApi
            //Assert.IsType<LimitUserController3s5m4mApi>(instance);
        }

        /// <summary>
        /// Test ApiLimitUserController3s5m4mGetGet
        /// </summary>
        [Fact]
        public void ApiLimitUserController3s5m4mGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiLimitUserController3s5m4mGetGet();
            //Assert.IsType<string>(response);
        }
    }
}
