openapi: 3.0.1
info:
  title: SampleLimitRequestWebApi
  version: "1.0"
servers:
- url: /
paths:
  /api/Count/Get_Normal:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: int32
                type: integer
            application/json:
              schema:
                format: int32
                type: integer
            text/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - Count
  /api/LimitAction3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitAction3s
  /api/LimitAction3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitAction3s5m
  /api/LimitAction3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitAction3s5m100h
  /api/LimitAction3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitAction3s5m4m
  /api/LimitController3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitController3s
  /api/LimitController3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitController3s5m
  /api/LimitController3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitController3s5m100h
  /api/LimitController3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitController3s5m4m
  /api/LimitIpAction3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpAction3s
  /api/LimitIpAction3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpAction3s5m
  /api/LimitIpAction3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpAction3s5m100h
  /api/LimitIpAction3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpAction3s5m4m
  /api/LimitIpController3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpController3s
  /api/LimitIpController3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpController3s5m
  /api/LimitIpController3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpController3s5m100h
  /api/LimitIpController3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitIpController3s5m4m
  /api/LimitUserAction3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserAction3s
  /api/LimitUserAction3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserAction3s5m
  /api/LimitUserAction3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserAction3s5m100h
  /api/LimitUserAction3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserAction3s5m4m
  /api/LimitUserController3s/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserController3s
  /api/LimitUserController3s5m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserController3s5m
  /api/LimitUserController3s5m100h/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserController3s5m100h
  /api/LimitUserController3s5m4m/Get:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - LimitUserController3s5m4m
  /api/RequestRateLimitStatus/GetStatus:
    post:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatus'
            application/json:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatus'
            text/json:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatus'
          description: Success
      tags:
      - RequestRateLimitStatus
  /api/RequestRateLimitStatus/GetStatusInfo:
    post:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatusInfo'
            application/json:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatusInfo'
            text/json:
              schema:
                $ref: '#/components/schemas/RequestRateLimitStatusInfo'
          description: Success
      tags:
      - RequestRateLimitStatus
  /api/Sample/Get_Normal:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Post_Normal:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Post_Limit10BytesSize:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Get_LimitGlobal1PreSecond:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Get_LimitGlobal3PreSecond5PerMinutes:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Get_LimitUser3PreSecond:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
  /api/Sample/Get_LimitGlobal5PreSecondUser3PreSecond:
    get:
      parameters:
      - explode: true
        in: query
        name: data
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Sample
components:
  schemas:
    RequestRateLimitStatus:
      additionalProperties: false
      example:
        updatedTime: 2000-01-23T04:56:07.000+00:00
        typesContainers:
          key:
          - updatedTime: 2000-01-23T04:56:07.000+00:00
            type: null
            items:
            - unit: null
              amount: 6
              limit: 0
            - unit: null
              amount: 6
              limit: 0
            key: key
          - updatedTime: 2000-01-23T04:56:07.000+00:00
            type: null
            items:
            - unit: null
              amount: 6
              limit: 0
            - unit: null
              amount: 6
              limit: 0
            key: key
      properties:
        updatedTime:
          format: date-time
          type: string
        typesContainers:
          additionalProperties:
            items:
              $ref: '#/components/schemas/RequestRateLimitStatusContainer'
            type: array
          nullable: true
          type: object
      type: object
    RequestRateLimitStatusContainer:
      additionalProperties: false
      example:
        updatedTime: 2000-01-23T04:56:07.000+00:00
        type: null
        items:
        - unit: null
          amount: 6
          limit: 0
        - unit: null
          amount: 6
          limit: 0
        key: key
      properties:
        key:
          nullable: true
          type: string
        updatedTime:
          format: date-time
          type: string
        type:
          $ref: '#/components/schemas/RequestRateLimitStatusContainerType'
        items:
          items:
            $ref: '#/components/schemas/RequestRateLimitStatusContainerItem'
          nullable: true
          type: array
      type: object
    RequestRateLimitStatusContainerItem:
      additionalProperties: false
      example:
        unit: null
        amount: 6
        limit: 0
      properties:
        unit:
          $ref: '#/components/schemas/RequestRateLimitStatusPerTimeUnit'
        limit:
          format: int32
          type: integer
        amount:
          format: int32
          type: integer
      type: object
    RequestRateLimitStatusContainerType:
      enum:
      - 0
      - 1
      - 2
      - 3
      format: int32
      type: integer
    RequestRateLimitStatusContainerTypeInfo:
      additionalProperties: false
      example:
        name: name
        description: description
        type: null
      properties:
        type:
          $ref: '#/components/schemas/RequestRateLimitStatusContainerType'
        name:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
      type: object
    RequestRateLimitStatusInfo:
      additionalProperties: false
      example:
        unitUnitInfos:
          key:
            unit: null
            name: name
        typeInfos:
        - name: name
          description: description
          type: null
        - name: name
          description: description
          type: null
      properties:
        typeInfos:
          items:
            $ref: '#/components/schemas/RequestRateLimitStatusContainerTypeInfo'
          nullable: true
          type: array
        unitUnitInfos:
          additionalProperties:
            $ref: '#/components/schemas/RequestRateLimitStatusPerTimeUnitInfo'
          nullable: true
          type: object
      type: object
    RequestRateLimitStatusPerTimeUnit:
      enum:
      - 0
      - 1
      - 2
      format: int32
      type: integer
    RequestRateLimitStatusPerTimeUnitInfo:
      additionalProperties: false
      example:
        unit: null
        name: name
      properties:
        unit:
          $ref: '#/components/schemas/RequestRateLimitStatusPerTimeUnit'
        name:
          nullable: true
          type: string
      type: object

