/* tslint:disable */
/* eslint-disable */
/**
 * SampleLimitRequestWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestRateLimitStatus,
} from '../models/index';
import {
    RequestRateLimitStatusFromJSON,
    RequestRateLimitStatusToJSON,
} from '../models/index';

/**
 * 
 */
export class RequestRateLimitStatusApi extends runtime.BaseAPI {

    /**
     */
    async apiRequestRateLimitStatusGetStatusPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestRateLimitStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/RequestRateLimitStatus/GetStatus`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestRateLimitStatusFromJSON(jsonValue));
    }

    /**
     */
    async apiRequestRateLimitStatusGetStatusPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestRateLimitStatus> {
        const response = await this.apiRequestRateLimitStatusGetStatusPostRaw(initOverrides);
        return await response.value();
    }

}
